%% CUNEC First-Order Path Loss Model with Correlated Shadowing
% This script computes and visualizes path loss using the CUNEC first-order model
% with spatially correlated log-normal shadowing across multiple Monte Carlo realizations.

%% Input Parameters
p_UE_2          = [0,  -30, 1.5];

p_corner_1      = [0 0 1.5];

p_corner_2      = [80 0 15];

p_AP_2          = zeros(200,3);
for i = 1:200
    p_AP_2(i,1) = 80;
    p_AP_2(i,2) = i;
    p_AP_2(i,3) = 15;
end

near_far        = "near";

building        = 60;
width           = 20;
height          = 15;            % Fixed street width (latent variable)
N_realizations = 1000;          % Number of Monte Carlo realizations

%% Load Model Parameters
run('load_model_parameters.m'); % Loads mu_1, sigma_1, etc.
run('load_correlations.m');     % Loads C_1 (correlation matrix)

%% Compute First-Order Path Loss with Correlated Shadowing
[D, PL_CUNEC_zeroth] = calc_PL_CUNEC_0th( ...
    p_corner_1, ...
    p_UE_2, ...
    building, ...
    width, ...
    height, ...
    FSPL_1m_3pt5GHz, ...
    mu_0, ...
    sigma_0, ...
    C_0, ...
    N_realizations);

PL_CUNEC_first = calc_PL_CUNEC_1st( ...
    p_corner_2, ...
    p_corner_1, ...
    p_corner_1, ...
    near_far, ...
    building, ...
    height, ...
    mu_1, ...
    sigma_1, ...
    C_1, ...
    N_realizations);

PL_CUNEC_second = calc_PL_CUNEC_2nd( ...
    p_AP_2, ...
    p_corner_2, ...
    p_corner_2, ...
    building, ...
    mu_2, ...
    sigma_2, ...
    C_2, ...
    N_realizations);

% Compute average path loss across all realizations
PL_all = PL_CUNEC_zeroth + PL_CUNEC_first + PL_CUNEC_second;

%% Plot Results
figure; hold on; grid on;

% Plot mean path loss curve
plot(5:5:60, mean(PL_all(:,5:5:60)), 'b-o', ...
    'LineWidth', 2, 'DisplayName', 'First-Order (Mean)');

% Plot formatting
xlabel('Distance from First Corner (m)', 'FontSize', 12);
ylabel('Added Path Loss From Corner (dB)', 'FontSize', 12);
title('CUNEC First-Order: Added Path Loss From Corner', 'FontSize', 14);
legend('Location', 'northwest');
set(gca, 'FontSize', 12);

mean_PL_CUNEC = mean(PL_all(:,5:60));
pathloss_final = PL_all(:,5:60);