%% CUNEC First-Order Path Loss Model with Correlated Shadowing
% This script computes and visualizes path loss using the CUNEC first-order model
% with spatially correlated log-normal shadowing across multiple Monte Carlo realizations.

%% Input Parameters
d1             = 1:1:200;       % Distance from the first corner to receiver (m)
trajectory     = 'AP';          % Choose 'AP' or 'UE'
width          = 20;            % Fixed street width (latent variable)
height         = 25;
dc1            = 80;           % Distance from TX to first corner (m)
N_realizations = 1000;          % Number of Monte Carlo realizations

%% Load Model Parameters
run('load_model_parameters.m'); % Loads mu_1, sigma_1, etc.
run('load_correlations.m');     % Loads C_1 (correlation matrix)

%% Compute First-Order Path Loss with Correlated Shadowing
PL_CUNEC_zeroth = calc_PL_CUNEC_0th( ...
    dc1, ...
    width, ...
    height, ...
    FSPL_1m_3pt5GHz, ...
    mu_0, ...
    sigma_0, ...
    C_0, ...
    N_realizations, ...
    trajectory);

PL_CUNEC_first = calc_PL_CUNEC_1st( ...
    d1, ...
    width, ...
    corner_dist_1_threshold, ...
    dc1, ...
    mu_1, ...
    sigma_1, ...
    C_1, ...
    N_realizations, ...
    trajectory);

% Compute average path loss across all realizations
mean_PL_first  = mean(PL_CUNEC_zeroth + PL_CUNEC_first, 1);

%% Plot Results
figure; hold on; grid on;

% Plot mean path loss curve
plot(d1, mean_PL_first, 'b-o', ...
    'LineWidth', 2, 'DisplayName', 'First-Order (Mean)');

% Plot formatting
xlabel('Distance from First Corner (m)', 'FontSize', 12);
ylabel('Added Path Loss From Corner (dB)', 'FontSize', 12);
title('CUNEC First-Order: Added Path Loss From Corner', 'FontSize', 14);
legend('Location', 'northwest');
set(gca, 'FontSize', 12);
